### ISSUE TITLE
UnboundLocalError: local variable 'parseqName' referenced before assignment

### ISSUE THREAD

**Issue by learn4fun2018** [rewbs/sd-parseq#161]
Deforum runs fine, with Parseq, I always get the same error:

Traceback (most recent call last):
  File "D:\sd-webui-aki-v4.2\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "D:\sd-webui-aki-v4.2\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "D:\sd-webui-aki-v4.2\extensions\deforum-for-automatic1111-webui\scripts\deforum.py", line 91, in run_deforum
    render_animation(args, anim_args, video_args, parseq_args, loop_args, root.animation_prompts, root)
  File "D:\sd-webui-aki-v4.2/extensions/deforum-for-automatic1111-webui/scripts\deforum_helpers\render.py", line 168, in render_animation
    scale = keys.cfg_scale_schedule_series[frame_idx]
  File "D:\sd-webui-aki-v4.2/extensions/deforum-for-automatic1111-webui/scripts\deforum_helpers\parseq_adapter.py", line 162, in __getattribute__
    logging.info(f"Data for {name} not defined in Parseq data (looked for: '{parseqName}'). Falling back to standard Deforum values.")

Please help

**Comment by rewbs** [comment]
This means you're on an old version of the Deforum extension. Please try updating to the latest version and let me know how it goes.

**Comment by learn4fun2018** [comment]
I have updated Deforum and Parseq to the latest.

Deforum-for-automatic1111-webui | https://gitcode.net/ranting8323/sd-webui-deforum.git | main | 2df3e15a | Thu Feb 2 18:51:58 2023 | latest
sd-parseq | https://github.com/rewbs/sd-parseq.git | master | c5c2b235 | Wed Jul 5 00:34:40 2023 | latest

But still got the same error.

I tried Deforum without Parseq, it works.

**Comment by rewbs** [comment]
> Deforum-for-automatic1111-webui | https://gitcode.net/ranting8323/sd-webui-deforum.git | main | 2df3e15a | Thu Feb 2 18:51:58 2023 | latest

That is not the latest deforum extension.  Looks like you are using someone's old fork.

You need to delete that extension and switch to using the official extension repository: https://github.com/deforum-art/sd-webui-deforum

**Comment by learn4fun2018** [comment]
Sovled, Yes, I installed the latest version of Deforum.
Thanks
