### ISSUE TITLE
No module named 'ffmpeg'

### ISSUE THREAD

**Issue by patrickmac110** [rewbs/sd-parseq#18]
I installed ffmpeg and followed the rest of your instructions, but I'm getting these errors upon launch:
Error loading script: parseq_core.py
Traceback (most recent call last):
  File "A:\Desktop\00 AI Images\stable-diffusion-webui\modules\scripts.py", line 159, in load_scripts
    exec(compiled, module.__dict__)
  File "A:\Desktop\00 AI Images\stable-diffusion-webui\scripts\parseq_core.py", line 10, in <module>
    import ffmpeg
ModuleNotFoundError: No module named 'ffmpeg'

Error loading script: parseq_script.py
Traceback (most recent call last):
  File "A:\Desktop\00 AI Images\stable-diffusion-webui\modules\scripts.py", line 159, in load_scripts
    exec(compiled, module.__dict__)
  File "A:\Desktop\00 AI Images\stable-diffusion-webui\scripts\parseq_script.py", line 8, in <module>
    from scripts.parseq_core import Parseq
  File "A:\Desktop\00 AI Images\stable-diffusion-webui\scripts\parseq_core.py", line 10, in <module>
    import ffmpeg
ModuleNotFoundError: No module named 'ffmpeg'

**Comment by rewbs** [comment]
Thanks for the report @patrickmac110 .

Could you share how you installed `ffmpeg-python`,  how you are launching `stable-diffusion-webui`, and what OS you are on? My guess is sd is running with a virtual env in which the module is not installed.

You could try adding the line `ffmpeg-python==0.2.0` to `requirements_versions.txt`, or `ffmpeg-python` to `requirements.txt`  (both those files are in your top-level sd directory). If you start SD with `launch.py`, it will resolve dependencies automatically from one of those two files depending on your OS.

**Comment by patrickmac110** [comment]
I installed ffmpeg by running pip install ffmpeg-python in a powershell window, I'm launching the webui by double-clicking the web-ui-use.bat file, on wndows 11. However, your seuggestion to include ffmpeg-python==0.2.0 in the requirements_versions.txt seemed to get rid of the error messages. Thanks!
