### ISSUE TITLE
Error when I try to execute the script

### ISSUE THREAD

**Issue by srcphag** [rewbs/sd-parseq#27]
I get this errors each time that I try to run the parsec script on img to img

Traceback (most recent call last):
  File "E:\Dev\stable-diffusion-webui\modules\call_queue.py", line 45, in f
    res = list(func(*args, **kwargs))
  File "E:\Dev\stable-diffusion-webui\modules\call_queue.py", line 28, in f
    res = func(*args, **kwargs)
  File "E:\Dev\stable-diffusion-webui\modules\img2img.py", line 137, in img2img
    processed = modules.scripts.scripts_img2img.run(p, *args)
  File "E:\Dev\stable-diffusion-webui\modules\scripts.py", line 317, in run
    processed = script.run(p, *script_args)
  File "E:\Dev\stable-diffusion-webui\scripts\parseq_script.py", line 44, in run
    [all_images, info] = Parseq().run(p, input_img=original_input_image_resized, input_path=input_path, output_path=output_path,
  File "E:\Dev\stable-diffusion-webui\scripts\parseq_core.py", line 93, in run
    ffmpeg
  File "E:\Dev\stable-diffusion-webui\venv\lib\site-packages\ffmpeg\_run.py", line 284, in run_async
    return subprocess.Popen(
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1440, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] El sistema no puede encontrar el archivo especificado

**Comment by srcphag** [comment]
The error was caused by no adding the ffmpeg library to the windows PATH. Adding ffmpeg dir to the PATH solves the issue. In any case, this need to be more clear in the install section of the documentation.
